### ISSUE TITLE
Reconnection attempts grow exponentially

### ISSUE THREAD

**Issue by mitchjmiller** [mwwhited/signalr-client-nodejs#13]
There seems to be an issue with the module where if the connection is lost and refused, the reconnection attempt works correctly for a number of iterations (5-10). It then however starts two connection attempts at a time, then three and so on until its attempting 100s of connection attempts at a time.

Once a connection is eventually established the issue disappears, but so long as the signalr service remains unavailable the connection pool will continue to grow until a successful connection is made.

My best guess from looking through the code is that the sockets event emitter is triggering twice (possible connection failure and timeout?) causing two connection attempts to occur. Then these two connection attempts fail the same resulting in the exponential growth. I haven't confirmed this, but this to me looks like the most likely suspect.

I'm aware that the creator is not actively working on this module and unfortunately I don't have the time to investigate this fully myself, but I said I would log the issue here in case anyone else is willing to take up the task.

**Comment by hoalby** [comment]
client.serviceHandlers.reconnecting = function (retry) {
    logger.info(`WS: reconnecting(inital: ${retry.inital} count: ${retry.count})`);
    return true;
};
client.serviceHandlers.disconnected = function() {
    logger.info('WS: disconnected');
    //restart();
};
client.serviceHandlers.onerror = function (error, statusCode) {
    logger.error('WS: onerror ==>> ', error, statusCode);
    restart();
};
client.serviceHandlers.connectionLost = function (error) {
    logger.error('WS: connectionLost ==>> ', error);
    restart();
};
client.serviceHandlers.connectFailed = function (error) {
    logger.error('WS: connectFailed ==>> ', error);
    restart();
};

client.start();

function restart() {
    setTimeout(function () {
        client.start();
    }, 2000);
}
