### ISSUE TITLE
Websocket onerror:  This client only supports websockets

### ISSUE THREAD

**Issue by sw-tt-mayankpatel** [mwwhited/signalr-client-nodejs#17]
When I try to connect this script I got following error.

Response in Console:
==================
clientInterface {
  url: [Getter],
  state: [Getter],
  handlers: [Getter/Setter],
  serviceHandlers: [Getter/Setter],
  hubs: [Getter],
  lastMessageId: [Getter],
  headers: [Getter/Setter],
  proxy: [Getter/Setter],
  queryString: [Getter/Setter],
  hub: [Function],
  on: [Function],
  end: [Function],
  invoke: [Function],
  callTimeout: [Getter/Setter],
  call: [Function],
  start: [Function] }
Waiting!
Websocket onerror:  This client only supports websockets
{ code: 0, desc: 'unbound' }
Websocket onerror:  This client only supports websockets
Client State Code:  0
Client State Description:  unbound
==>> try to get hub
==>> hub not found. retry in 10 seconds
Error:
==============================================
Websocket onerror:  This client only supports websockets
{ code: 0, desc: 'unbound' }
Websocket onerror:  This client only supports websockets
{ code: 0, desc: 'unbound' }
Websocket onerror:  This client only supports websockets
{ code: 0, desc: 'unbound' }
Websocket onerror:  This client only supports websockets
{ code: 0, desc: 'unbound' }
Websocket onerror:  This client only supports websockets
{ code: 0, desc: 'unbound' }
Websocket onerror:  This client only supports websockets
==============================================
Client State Code:  0
Client State Description:  unbound

Kindly look forward to it and give positive feedback.

I am looking forward to hearing from you.

Thanks

**Comment by mwwhited** [comment]
It looks like your hub is using long polling instead of websockets.  This client only supports websockets.

**Comment by sw-tt-mayankpatel** [comment]
What I need to do next..? any idea?

**Comment by vincemic** [comment]
Where is the hub you are trying to connect to hosted? Is it local IIS, a server, or in a cloud like Azure?

**Comment by vincemic** [comment]
If its Azure, you need to make sure that you have enabled websockets on the site instance.

**Comment by sw-tt-mayankpatel** [comment]
Yes, it is on Azure.

**Comment by mwwhited** [comment]
The signalR hub must support and be configured to enable websockets support.  This client does not support any other transport.
