### ISSUE TITLE
“WebSocketClient is not a constructor” in Browser

### ISSUE THREAD

**Issue by wenxiayili** [mwwhited/signalr-client-nodejs#18]
vue.esm.js?65d7:479 [Vue warn]: Error in created hook: "TypeError: WebSocketClient is not a constructor"

found in

---> <Test> at F:\学习\csshtml\VueStart\src\SignalR\Test.vue
       <App> at F:\学习\csshtml\VueStart\src\App.vue
         <Root>
warn @ vue.esm.js?65d7:479
handleError @ vue.esm.js?65d7:562
callHook @ vue.esm.js?65d7:2667
Vue._init @ vue.esm.js?65d7:4226
VueComponent @ vue.esm.js?65d7:4396
createComponentInstanceForVnode @ vue.esm.js?65d7:3678
init @ vue.esm.js?65d7:3495
createComponent @ vue.esm.js?65d7:5147
createElm @ vue.esm.js?65d7:5090
updateChildren @ vue.esm.js?65d7:5370
patchVnode @ vue.esm.js?65d7:5445
patch @ vue.esm.js?65d7:5575
Vue._update @ vue.esm.js?65d7:2424
updateComponent @ vue.esm.js?65d7:2538
get @ vue.esm.js?65d7:2881
run @ vue.esm.js?65d7:2958
flushSchedulerQueue @ vue.esm.js?65d7:2724
(anonymous) @ vue.esm.js?65d7:701
nextTickHandler @ vue.esm.js?65d7:648
Promise resolved (async)
timerFunc @ vue.esm.js?65d7:663
queueNextTick @ vue.esm.js?65d7:711
queueWatcher @ vue.esm.js?65d7:2811
update @ vue.esm.js?65d7:2948
notify @ vue.esm.js?65d7:778
reactiveSetter @ vue.esm.js?65d7:1000
(anonymous) @ vue-router.esm.js?880d:2390
(anonymous) @ vue-router.esm.js?880d:2389
updateRoute @ vue-router.esm.js?880d:1924
(anonymous) @ vue-router.esm.js?880d:1802
(anonymous) @ vue-router.esm.js?880d:1911
step @ vue-router.esm.js?880d:1649
step @ vue-router.esm.js?880d:1656
runQueue @ vue-router.esm.js?880d:1660
(anonymous) @ vue-router.esm.js?880d:1906
step @ vue-router.esm.js?880d:1649
(anonymous) @ vue-router.esm.js?880d:1653
(anonymous) @ vue-router.esm.js?880d:1891
(anonymous) @ vue-router.esm.js?880d:1692
(anonymous) @ vue-router.esm.js?880d:1760
(anonymous) @ main.js?1c90:19
Promise resolved (async)
component @ main.js?1c90:19
(anonymous) @ vue-router.esm.js?880d:1709
(anonymous) @ vue-router.esm.js?880d:1736
(anonymous) @ vue-router.esm.js?880d:1736
flatMapComponents @ vue-router.esm.js?880d:1735
(anonymous) @ vue-router.esm.js?880d:1671
iterator @ vue-router.esm.js?880d:1870
step @ vue-router.esm.js?880d:1652
step @ vue-router.esm.js?880d:1656
runQueue @ vue-router.esm.js?880d:1660
confirmTransition @ vue-router.esm.js?880d:1899
transitionTo @ vue-router.esm.js?880d:1801
init @ vue-router.esm.js?880d:2381
beforeCreate @ vue-router.esm.js?880d:500
callHook @ vue.esm.js?65d7:2665
Vue._init @ vue.esm.js?65d7:4222
Vue$3 @ vue.esm.js?65d7:4321
(anonymous) @ main.js?1c90:62
(anonymous) @ app.js:1543
__webpack_require__ @ app.js:689
fn @ app.js:110
(anonymous) @ app.js:1783
__webpack_require__ @ app.js:689
(anonymous) @ app.js:790
(anonymous) @ app.js:793
20:01:44.191 vue.esm.js?65d7:566 TypeError: WebSocketClient is not a constructor
    at new clientInterface (signalR.js?64a0:328)
    at VueComponent.init (Test.vue?8e23:17)
    at VueComponent.boundFn [as init] (vue.esm.js?65d7:183)
    at VueComponent.created (Test.vue?8e23:12)
    at callHook (vue.esm.js?65d7:2665)
    at VueComponent.Vue._init (vue.esm.js?65d7:4226)
    at new VueComponent (vue.esm.js?65d7:4396)
    at createComponentInstanceForVnode (vue.esm.js?65d7:3678)
    at init (vue.esm.js?65d7:3495)
    at createComponent (vue.esm.js?65d7:5147)

**Comment by wenxiayili** [comment]
thank you ...

**Comment by mwwhited** [comment]
This package is a server side client for node.js.  It is not supported in the browser.  Use the signalR client from Microsoft.
