### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by wenxiayili** [mwwhited/signalr-client-nodejs#19]
params:
clientProtocol	"1.5"
transport	"webSockets"
connectionToken	"kCVWZwinGBB87gq/mj5/0IbcTOHgr…imAxgIgzqPjAMgH7TLeTNIUeEHa1"
connectionData	"[{\"name\":\"chathub\"}]"
tid	"10"
![image](https://user-images.githubusercontent.com/24307095/29446262-d8433bd2-841d-11e7-94d2-c6ec8dce7756.png)

**Comment by mwwhited** [comment]
This package is a server side client for node.js.  It is not supported in the browser.  Use the signalR client from Microsoft.
