### ISSUE TITLE
Please do not use `console.log` directly in the module

### ISSUE THREAD

**Issue by moltar** [mwwhited/signalr-client-nodejs#21]
It pollutes the output. I'd recommend to just use an optional logging library hook and silence it otherwise.

This is an example of one case, but there are more than 1.

https://github.com/mwwhited/signalr-client-nodejs/blob/a68660bc1a604cb6f512f01febff7fc115348c48/WhitedUS.SignalR/WhitedUS.signalR/signalR.js#L705

**Comment by moltar** [comment]
Can send a PR, if you would accept.

**Comment by mwwhited** [comment]
If anyone want to provide pull requests feel free... FYI I typically blindly accept them so be warned as I'm not actively maintaining and no one has offered to help.

**Comment by mwwhited** [comment]
And I thought I only logged errors by default.  I believe they can be disabled by binding your own handler.
