### ISSUE TITLE
Unable to get the Disconnected handler to fire

### ISSUE THREAD

**Issue by fallenfate1982** [mwwhited/signalr-client-nodejs#22]
Using the handler code from the sample, I'm getting connected and bound to fire as well as message received. However connectionlost and disconnected do not fire even when the network is killed.

I'm running node JS on a Raspberry Pi. All other functions seem to work as expected.

**Comment by danielvieira43** [comment]
I'm with the same problem. Any ideas? It's important to keep track of connection status... 

Tks!
