### ISSUE TITLE
Problem when connect to signalR hub hosted on IIS

### ISSUE THREAD

**Issue by dragonlong206** [mwwhited/signalr-client-nodejs#26]
Hi
We tried to use your library to connect from a nodejs server to an ASP.NET MVC application hosted on IIS. Because you only support WebSockets protocol, we encounter error "This client only supports websockets". We thought the problem was on client side and took a whole day for investigating the problem. Finally, today we find out that the problem is server does not enable WebSocket protocol. Refer to this link https://stackoverflow.com/a/41892056/3900093. I think you should document it on your documentation. It will help later users.
Thanks

**Comment by tanmynguyen** [comment]
Thanks Bro!!. I tried and resolved issue.  💯

**Comment by mwwhited** [comment]
That's the first thing in the README on both github and npm.

**Comment by dragonlong206** [comment]
Hi MWWhited,
I'm not talking about you support WebSocket only. I'm talking about enabling WebSocket protocol feature on Windows server.
