### ISSUE TITLE
negotiate:unknown 404 error

### ISSUE THREAD

**Issue by umasgn** [mwwhited/signalr-client-nodejs#3]
Hi i'm trying to use your signlar-client-nodejs npm package for signlar hub,
i'm getting this error negotiate: unknown 404 error.

**Comment by mwwhited** [comment]
This is a signalr client not a hub.  What version is your hub and could you provide me with some of your code?

-----Original Message-----

**Comment by umasgn** [comment]
var signalR = require('signalr-client');
var client = new signalR.client("http://xxxxx.azurewebsites.net/", ['motorsHub'],10,false);

client.invoke(
    'motorsHub', // Hub Name (case insensitive)
    'DeviceConnected', // Method Name (case insensitive)
    'Motor1', 'Hyderabad' ,'Admin'//additional parameters to match signature
);

**Comment by mwwhited** [comment]
The client URI needs to be the full path to your hub. try something like http://xxxxx.azurewebsites.net/signalR

**Comment by umasgn** [comment]
http://xxxxx.azurewebsites.net/Hubs/MotorsHub   (MotorsHub.cs)
still getting the same error.

**Comment by mwwhited** [comment]
okay... I should have said the signalR endpoint not full path to your hub. Where is your .MapSignalR() mapped in your host?  If you are calling .MapSignalR() with not parameters your URL should end in /signalR.  If you changed the mapping path then you will want to use that instead.

**Comment by umasgn** [comment]
Hi mwwhited, i've tried that url too. http://xxxxx.azurewebsites.net/Hubs, http://xxxxx.azurewebsites.net http://xxxxx.azurewebsites.net/Hubs/MotorsHub, i didn't change any mapping path. it is working fine in the app from javascript front end. unable to use your npm package. i'll be very help to you, if you help me though this. are there any working examples ?

**Comment by mwwhited** [comment]
The signalr-samples.js and the README.js both have client examples.  Look at the proxy classes generated by the signalR service.  In your page js you should see a script reference something like /signalr/hubs if you access that directly from a browser you can scroll to the bottom and see what the proper url is for your endpoint. 


As a note I’ve been assuming you redacted your hostname and you are not really using xxxxx. In your url.  I am also assuming you are not using ssl or any sort of authentication on your endpoint.





From: umasgn
Sent: ‎Monday‎, ‎August‎ ‎10‎, ‎2015 ‎11‎:‎27‎ ‎PM
To: mwwhited/signalr-client-nodejs
Cc: Matthew Whited





Hi mwwhited, i've tried that url too. http://xxxxx.azurewebsites.net/Hubs, http://xxxxx.azurewebsites.net http://xxxxx.azurewebsites.net/Hubs/MotorsHub, i didn't change any mapping path. it is working fine in the app from javascript front end. unable to use your npm package. i'll be very help to you, if you help me though this. are there any working examples ?

**Comment by umasgn** [comment]
Please give me your gmail id, so that we can chat online. i'm getting same errors. if you give me the email i'll share complete information about our end point.

**Comment by mwwhited** [comment]
Matt@whited.us






From: umasgn
Sent: ‎Tuesday‎, ‎August‎ ‎11‎, ‎2015 ‎8‎:‎33‎ ‎AM
To: mwwhited/signalr-client-nodejs
Cc: Matthew Whited





Please give me your gmail id, so that we can chat online. i'm getting same errors. if you give me the email i'll share complete information about our end point.

**Comment by mwwhited** [comment]
ensure that the cilent is using the correct URL for the signalR endpoint.  This is typically similar to http://yourdomain.com/signalR

if you want to do something after the connection is established you need to add the call to the connected serviceHandler.

client.serviceHandlers = {
    connected: function (connection) {
        console.log("Websocket connected");

        afterConnect(); // if you want to do something after connected you should put it here
    }
};
