### ISSUE TITLE
Problem using https

### ISSUE THREAD

**Issue by phinzphinz** [mwwhited/signalr-client-nodejs#30]
I have absolutely no experience with signalr but I tried to connect to bittrex. The following does not work:

```
var signalR = require('signalr-client');
var client  = new signalR.client(
	"http://socket.bittrex.com/signalr",
	['c2']
);
```
```
Error Message:  Protocol Error
Exception:  undefined
Error Data:  Url {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'socket.bittrex.com',
  port: null,
  hostname: 'socket.bittrex.com',
  hash: null,
  search:
   '?connectionData=%5B%7B%22name%22%3A%22c2%22%7D%5D&clientProtocol=1.5',
  query: { connectionData: '[{"name":"c2"}]', clientProtocol: '1.5' },
  pathname: '/signalr/negotiate',
  path:
   '/signalr/negotiate?connectionData=%5B%7B%22name%22%3A%22c2%22%7D%5D&clientProtocol=1.5',
  href:
   'https://socket.bittrex.com/signalr/negotiate?connectionData=%5B%7B%22name%22%3A%22c2%22%7D%5D&clientProtocol=1.5',
  headers: {} }
undefined
```
But when I replace 'https' by 'http', it works (there is no error and it logs `Connected!`.

**Comment by n0mad01** [comment]
wrong uri, take a look here:
https://github.com/n0mad01/bittrex.github.io/blob/master/samples/WebsocketSample.js

**Comment by phinzphinz** [comment]
OK thank you, I had the uri from: https://github.com/Bittrex/bittrex.github.io#connecting
`The WS API endpoint is https://socket.bittrex.com/signalr. Once connected, be sure to connect to the c2 hub. No other hubs are supported for use by Bittrex customers.`
