### ISSUE TITLE
docker swarm

### ISSUE THREAD

**Issue by 93Kamuran** [mwwhited/signalr-client-nodejs#33]
ı want to use it in docker swarm behind traefik reverse proxy.   when ı run that as a docker container the client can connect to my signalR hub is that in running another service in my swarm. But could not invoke the method in the hub.  Sadly when I try to use this node.js app in my swarm.  node.js api cannot  connect to hub
 
ı see this error 

Websocket bindingError:  { Error: connect ECONNREFUSED 178.211.50.93:443

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)

  errno: 'ECONNREFUSED',

  code: 'ECONNREFUSED',

  syscall: 'connect',

  address: 'x.x.x',

  port: 443 }

**Comment by mwwhited** [comment]
This error typically means the server is using HTTPS but your connection string is trying HTTP
