### ISSUE TITLE
"Connection aborted" but application does not terminate.

### ISSUE THREAD

**Issue by barl0g** [mwwhited/signalr-client-nodejs#35]
I receive a message "Connection aborted" but application does not terminate.

Why doesn't aborting the connection cause the program to terminate?

How to correctly reconnect or terminate the program with this error?

**Comment by mwwhited** [comment]
It should be trying to reconnect.  If you want it to do something different post a PR or fork the library.  I haven't used this or maintained it in years.  

there are at least two other options to try if you don't like this library.

https://www.npmjs.com/package/@microsoft/signalr
https://www.npmjs.com/package/signalr
