### ISSUE TITLE
Can't retrieve connection id.

### ISSUE THREAD

**Issue by NightkingCH** [mwwhited/signalr-client-nodejs#4]
Hi there. First of all, thanks for your library!

I'm struggling to retrieve the signalR connection id. With the jquery signalR library I can do something like this: 

```javascript
var signalrClientId = $.connection.hub.connection.id;
```

But so far as I see, you wrap this inside:

```javascript
var _client = {
connection: {
            state: states.connection.unbound,
            token: null,
            id: null
        }
};
```

Is it possible that you could expose the connection object through a getter, something like this:

```javascript
client.__defineGetter__('connection', function () {
        return _client.connection;
    });
```

Or is there another way to obtain the id? I need this to map my signalR connections to a known id.

Thanks in advance for your help!

**Comment by mwwhited** [comment]
Check out the "connected" service handle.  The connectionToken and connectionId will not be populated until after a connection is established. 

-Thanks,
Matt

-----Original Message-----

**Comment by mwwhited** [comment]
Sorry, you are correct that I never exposed this in the client. I didn't really see a need as the hub knows your connectionId on every call.  Having a message that allows the client to tell the hub what connectionId it thinks is correct opens you for a spoof attack. I can look at adding this value but I'd suggest you should consider changing how you get this information on the hub side of your signalR service.

**Comment by mwwhited** [comment]
You should have the entire connection object on the connect and reconnect serviceHandles.
