### ISSUE TITLE
Unable to handle invoke

### ISSUE THREAD

**Issue by boxxa** [mwwhited/signalr-client-nodejs#6]
If I run:
```
client.invoke('myhub','updateSummary')
```

I have setup a handler:
```
client.handlers.myhub= {
 updatesummary: function(summarydata) {
  console.log("updatesummaryhandler");
 }
}
```

But I am unable to fire the handler when the invoke completes with the data that gets sent out. Is this possible at all through the SignalR protocol or would I need to parse the raw message?

**Comment by mwwhited** [comment]
Handlers are case sensitive so try `updateSummary: …` instead.  

Also, `client.invoke(…)` sends a message to the server hub.  `client.handlers.updateSummary` receives messages from the server hub.
