### ISSUE TITLE
Add Variables to the connections query string

### ISSUE THREAD

**Issue by voicemart** [mwwhited/signalr-client-nodejs#8]
Hi Matthew,

The subject only works for the stages other than /negotiate.
I believe you need to add the code below to fix it:
if (_client.queryString) {
        for (var propName in _client.queryString) {
            qs[propName] = _client.queryString[propName];
        }
}
which can be found in /start /connect /abort handlers.

**Comment by mwwhited** [comment]
Test it out and submit a pull request.
